import "server-only";

import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";

import type { AuthUser } from "@/lib/auth";
import { getAgentRuntimeSummary } from "@/lib/config";
import { executeQuery, queryOne, queryRows, withTransaction } from "@/lib/db";
import { resetAgentThread } from "@/lib/deep-agent";
import type {
  SkillBarMessage,
  SkillBarParticipant,
  SkillBarSnapshot,
} from "@/lib/skillbar-types";

type ParticipantRow = {
  id: string;
  user_id: string;
  name: string;
  kind: "human" | "agent";
  skill_content: string | null;
  thread_id: string | null;
  last_seen_seq: number;
  needs_greeting: boolean;
  status: "idle" | "thinking" | "error";
  last_error: string | null;
  created_at: number;
  updated_at: number;
};

type MessageRow = {
  seq: number;
  id: string;
  user_id: string;
  sender_id: string | null;
  sender_name: string;
  sender_kind: "human" | "agent" | "system";
  content: string;
  created_at: number;
};

type PendingSummaryRow = {
  latestSeq: number | null;
  total: number;
};

export type AgentRecord = {
  id: string;
  name: string;
  skillContent: string;
  threadId: string;
  lastSeenSeq: number;
  needsGreeting: boolean;
  status: "idle" | "thinking" | "error";
  lastError: string | null;
  createdAt: number;
  updatedAt: number;
};

export type AgentWork =
  | {
      kind: "greeting";
      userId: string;
      agent: AgentRecord;
      visibleSeq: number;
      members: string[];
    }
  | {
      kind: "reply";
      userId: string;
      agent: AgentRecord;
      visibleSeq: number;
      members: string[];
      messages: SkillBarMessage[];
      omittedCount: number;
    };

const HUMAN_ID_PREFIX = "human:";
const APP_TABLES_SQL = `
  CREATE TABLE IF NOT EXISTS participants (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('human', 'agent')),
    skill_content TEXT,
    thread_id TEXT UNIQUE,
    last_seen_seq INTEGER NOT NULL DEFAULT 0,
    needs_greeting BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle', 'thinking', 'error')),
    last_error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE(user_id, name)
  );

  CREATE TABLE IF NOT EXISTS messages (
    seq INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL,
    sender_id TEXT,
    sender_name TEXT NOT NULL,
    sender_kind TEXT NOT NULL CHECK (sender_kind IN ('human', 'agent', 'system')),
    content TEXT NOT NULL,
    created_at BIGINT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_participants_user_kind
    ON participants(user_id, kind);

  CREATE INDEX IF NOT EXISTS idx_messages_user_seq
    ON messages(user_id, seq);
`;

const globalForStore = globalThis as typeof globalThis & {
  __skillBarWebsiteStoreInitialization?: Promise<void>;
  __skillBarWebsiteStoreInitialized?: boolean;
};

function now() {
  return Date.now();
}

async function ensureAppTables() {
  if (globalForStore.__skillBarWebsiteStoreInitialized) {
    return;
  }

  if (!globalForStore.__skillBarWebsiteStoreInitialization) {
    globalForStore.__skillBarWebsiteStoreInitialization = executeQuery(APP_TABLES_SQL)
      .then(() => {
        globalForStore.__skillBarWebsiteStoreInitialized = true;
      })
      .finally(() => {
        if (!globalForStore.__skillBarWebsiteStoreInitialized) {
          globalForStore.__skillBarWebsiteStoreInitialization = undefined;
        }
      });
  }

  await globalForStore.__skillBarWebsiteStoreInitialization;
}

function displayNameFromUser(user: Pick<AuthUser, "email" | "name">) {
  if (user.name?.trim()) {
    return user.name.trim();
  }

  const [prefix] = user.email.split("@");
  return prefix || "Workspace Owner";
}

function humanIdFromUserId(userId: string) {
  return `${HUMAN_ID_PREFIX}${userId}`;
}

function createThreadId(userId: string, agentId: string) {
  return `skillbar:${userId}:${agentId}:${randomUUID()}`;
}

async function ensureWorkspaceOwner(user: Pick<AuthUser, "email" | "id" | "name">) {
  await ensureAppTables();

  const id = humanIdFromUserId(user.id);
  const displayName = displayNameFromUser(user);
  const timestamp = now();

  await executeQuery(
    `
      INSERT INTO participants (
        id,
        user_id,
        name,
        kind,
        skill_content,
        thread_id,
        last_seen_seq,
        needs_greeting,
        status,
        last_error,
        created_at,
        updated_at
      ) VALUES ($1, $2, $3, 'human', NULL, NULL, 0, FALSE, 'idle', NULL, $4, $5)
      ON CONFLICT (id) DO UPDATE
      SET
        name = EXCLUDED.name,
        updated_at = EXCLUDED.updated_at
    `,
    [id, user.id, displayName, timestamp, timestamp],
  );
}

function mapParticipant(row: ParticipantRow): SkillBarParticipant {
  return {
    createdAt: Number(row.created_at),
    hasThread: Boolean(row.thread_id),
    id: row.id,
    kind: row.kind,
    lastError: row.last_error,
    name: row.name,
    needsGreeting: Boolean(row.needs_greeting),
    status: row.status,
    updatedAt: Number(row.updated_at),
  };
}

function mapMessage(row: MessageRow): SkillBarMessage {
  return {
    content: row.content,
    createdAt: Number(row.created_at),
    id: row.id,
    senderId: row.sender_id,
    senderKind: row.sender_kind,
    senderName: row.sender_name,
    seq: Number(row.seq),
  };
}

function mapAgent(row: ParticipantRow): AgentRecord {
  return {
    createdAt: Number(row.created_at),
    id: row.id,
    lastError: row.last_error,
    lastSeenSeq: Number(row.last_seen_seq),
    name: row.name,
    needsGreeting: Boolean(row.needs_greeting),
    skillContent: row.skill_content ?? "",
    status: row.status,
    threadId: row.thread_id ?? createThreadId(row.user_id, row.id),
    updatedAt: Number(row.updated_at),
  };
}

async function insertMessage(
  userId: string,
  senderId: string | null,
  senderName: string,
  senderKind: "human" | "agent" | "system",
  content: string,
  client?: PoolClient,
) {
  await executeQuery(
    `
      INSERT INTO messages (
        id,
        user_id,
        sender_id,
        sender_name,
        sender_kind,
        content,
        created_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7)
    `,
    [randomUUID(), userId, senderId, senderName, senderKind, content, now()],
    client,
  );
}

async function getLatestSeq(userId: string) {
  const row = await queryOne<{ latestseq: number | null }>(
    `
      SELECT COALESCE(MAX(seq), 0)::int AS latestseq
      FROM messages
      WHERE user_id = $1
    `,
    [userId],
  );

  return Number(row?.latestseq ?? 0);
}

async function listParticipantRows(userId: string) {
  return queryRows<ParticipantRow>(
    `
      SELECT
        id,
        user_id,
        name,
        kind,
        skill_content,
        thread_id,
        last_seen_seq,
        needs_greeting,
        status,
        last_error,
        created_at,
        updated_at
      FROM participants
      WHERE user_id = $1
      ORDER BY CASE kind WHEN 'human' THEN 0 ELSE 1 END, created_at ASC
    `,
    [userId],
  );
}

async function listMessageRows(userId: string) {
  return queryRows<MessageRow>(
    `
      SELECT
        seq,
        id,
        user_id,
        sender_id,
        sender_name,
        sender_kind,
        content,
        created_at
      FROM messages
      WHERE user_id = $1
      ORDER BY seq ASC
    `,
    [userId],
  );
}

async function getAgentRows() {
  return queryRows<ParticipantRow>(
    `
      SELECT
        id,
        user_id,
        name,
        kind,
        skill_content,
        thread_id,
        last_seen_seq,
        needs_greeting,
        status,
        last_error,
        created_at,
        updated_at
      FROM participants
      WHERE kind = 'agent'
      ORDER BY updated_at ASC, created_at ASC
    `,
  );
}

async function getVisibleMessageSummary(userId: string, agentId: string, lastSeenSeq: number) {
  return queryOne<PendingSummaryRow>(
    `
      SELECT
        COUNT(*)::int AS total,
        MAX(seq)::int AS "latestSeq"
      FROM messages
      WHERE user_id = $1
        AND seq > $2
        AND (sender_id IS NULL OR sender_id != $3)
    `,
    [userId, lastSeenSeq, agentId],
  );
}

async function getVisibleMessages(
  userId: string,
  agentId: string,
  lastSeenSeq: number,
  limit = 18,
) {
  return queryRows<MessageRow>(
    `
      SELECT * FROM (
        SELECT
          seq,
          id,
          user_id,
          sender_id,
          sender_name,
          sender_kind,
          content,
          created_at
        FROM messages
        WHERE user_id = $1
          AND seq > $2
          AND (sender_id IS NULL OR sender_id != $3)
        ORDER BY seq DESC
        LIMIT $4
      ) visible_messages
      ORDER BY seq ASC
    `,
    [userId, lastSeenSeq, agentId, limit],
  );
}

export async function getSnapshot(user: Pick<AuthUser, "email" | "id" | "name">) {
  await ensureWorkspaceOwner(user);

  const [latestSeq, messages, participants] = await Promise.all([
    getLatestSeq(user.id),
    listMessageRows(user.id),
    listParticipantRows(user.id),
  ]);

  return {
    latestSeq,
    messages: messages.map(mapMessage),
    participants: participants.map(mapParticipant),
    workspace: {
      ownerName: displayNameFromUser(user),
      runtime: getAgentRuntimeSummary(),
      title: "SkillBar Workspace",
    },
  } satisfies SkillBarSnapshot;
}

export async function upsertAgentFromSkill(
  user: Pick<AuthUser, "email" | "id" | "name">,
  name: string,
  skillContent: string,
) {
  await ensureWorkspaceOwner(user);

  const trimmedName = name.trim();
  const trimmedSkill = skillContent.trim();

  if (!trimmedName) {
    throw new Error("这个 Skill 的原主人姓名不能为空。");
  }

  if (!trimmedSkill) {
    throw new Error("SKILL.md 不能为空。");
  }

  const existing = await queryOne<ParticipantRow>(
    `
      SELECT
        id,
        user_id,
        name,
        kind,
        skill_content,
        thread_id,
        last_seen_seq,
        needs_greeting,
        status,
        last_error,
        created_at,
        updated_at
      FROM participants
      WHERE user_id = $1 AND name = $2
    `,
    [user.id, trimmedName],
  );

  if (existing && existing.kind !== "agent") {
    throw new Error(`名字“${trimmedName}”已经被占用。`);
  }

  const timestamp = now();

  if (existing?.thread_id) {
    await resetAgentThread(existing.thread_id);
  }

  await withTransaction(async (client) => {
    if (existing) {
      await executeQuery(
        `
          UPDATE participants
          SET
            skill_content = $1,
            thread_id = $2,
            last_seen_seq = 0,
            needs_greeting = TRUE,
            status = 'idle',
            last_error = NULL,
            updated_at = $3
          WHERE id = $4
        `,
        [trimmedSkill, createThreadId(user.id, existing.id), timestamp, existing.id],
        client,
      );

      await insertMessage(
        user.id,
        null,
        "System",
        "system",
        `${trimmedName} 带着新的 Skill 重新进入了房间。`,
        client,
      );

      return;
    }

    const agentId = randomUUID();

    await executeQuery(
      `
        INSERT INTO participants (
          id,
          user_id,
          name,
          kind,
          skill_content,
          thread_id,
          last_seen_seq,
          needs_greeting,
          status,
          last_error,
          created_at,
          updated_at
        ) VALUES ($1, $2, $3, 'agent', $4, $5, 0, TRUE, 'idle', NULL, $6, $7)
      `,
      [agentId, user.id, trimmedName, trimmedSkill, createThreadId(user.id, agentId), timestamp, timestamp],
      client,
    );

    await insertMessage(
      user.id,
      null,
      "System",
      "system",
      `${trimmedName} 进入了房间。`,
      client,
    );
  });

  return getSnapshot(user);
}

export async function addUserMessage(
  user: Pick<AuthUser, "email" | "id" | "name">,
  content: string,
) {
  await ensureWorkspaceOwner(user);

  const trimmed = content.trim();

  if (!trimmed) {
    throw new Error("消息不能为空。");
  }

  await insertMessage(user.id, humanIdFromUserId(user.id), displayNameFromUser(user), "human", trimmed);

  return getSnapshot(user);
}

export async function addAgentMessage(userId: string, agentId: string, content: string) {
  const row = await queryOne<{ name: string }>(
    `
      SELECT name
      FROM participants
      WHERE id = $1 AND user_id = $2
    `,
    [agentId, userId],
  );

  if (!row) {
    throw new Error("找不到对应的 agent。");
  }

  await insertMessage(userId, agentId, row.name, "agent", content.trim());
}

export async function markAgentThinking(agentId: string) {
  await executeQuery(
    `
      UPDATE participants
      SET
        status = 'thinking',
        last_error = NULL,
        updated_at = $1
      WHERE id = $2
    `,
    [now(), agentId],
  );
}

export async function markAgentError(agentId: string, errorMessage: string) {
  await executeQuery(
    `
      UPDATE participants
      SET
        status = 'error',
        last_error = $1,
        updated_at = $2
      WHERE id = $3
    `,
    [errorMessage, now(), agentId],
  );
}

export async function completeAgentTurn(agentId: string, result: { visibleSeq: number }) {
  await executeQuery(
    `
      UPDATE participants
      SET
        last_seen_seq = $1,
        needs_greeting = FALSE,
        status = 'idle',
        last_error = NULL,
        updated_at = $2
      WHERE id = $3
    `,
    [result.visibleSeq, now(), agentId],
  );
}

export async function getPendingAgentWork(limit: number) {
  await ensureAppTables();

  const workItems: AgentWork[] = [];
  const memberNamesByUser = new Map<string, Promise<string[]>>();

  for (const row of await getAgentRows()) {
    if (workItems.length >= limit) {
      break;
    }

    const agent = mapAgent(row);
    const summary = await getVisibleMessageSummary(row.user_id, row.id, row.last_seen_seq);
    const shouldGreet = agent.needsGreeting;
    const hasVisibleUpdates = (summary?.total ?? 0) > 0;

    if (!shouldGreet && !hasVisibleUpdates) {
      continue;
    }

    if (!memberNamesByUser.has(row.user_id)) {
      memberNamesByUser.set(
        row.user_id,
        listParticipantRows(row.user_id).then((participants) => participants.map((participant) => participant.name)),
      );
    }

    const members = await memberNamesByUser.get(row.user_id)!;
    const visibleSeq = summary?.latestSeq ?? row.last_seen_seq;

    if (shouldGreet) {
      workItems.push({
        agent,
        kind: "greeting",
        members,
        userId: row.user_id,
        visibleSeq,
      });
      continue;
    }

    const messages = (await getVisibleMessages(row.user_id, row.id, row.last_seen_seq)).map(mapMessage);

    workItems.push({
      agent,
      kind: "reply",
      members,
      messages,
      omittedCount: Math.max((summary?.total ?? 0) - messages.length, 0),
      userId: row.user_id,
      visibleSeq,
    });
  }

  return workItems;
}
